// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwCEXgYW9y1war8Xp_DNKCXrV8atCbdgU',
    appId: '1:381848342958:web:dc1df661fa66bad331783f',
    messagingSenderId: '381848342958',
    projectId: 'signin-demo-f7a31',
    authDomain: 'signin-demo-f7a31.firebaseapp.com',
    storageBucket: 'signin-demo-f7a31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8DIYNcGy1RTLWUFEQEuZNyGhg5aH6MU0',
    appId: '1:381848342958:android:ae6187dfb741e61d31783f',
    messagingSenderId: '381848342958',
    projectId: 'signin-demo-f7a31',
    storageBucket: 'signin-demo-f7a31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfNdcWE8TXmmPbYs3tLaXdlwPpRcIwScA',
    appId: '1:381848342958:ios:c617eb2ea706e14f31783f',
    messagingSenderId: '381848342958',
    projectId: 'signin-demo-f7a31',
    storageBucket: 'signin-demo-f7a31.firebasestorage.app',
    iosClientId: '381848342958-vfa3c8g6seojd4r0di5nh6kduvahka22.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSigninDemo',
  );

}